server:
  port: 8082


spring:
  application:
    name: spring-cloud-reactive-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: rootroot
  redis:
    database: 0 #??????0?
    host: 127.0.0.1
    password: 123456  #?????????
    timeout: 5000 #??????????
    lettuce:
      pool:
        max-idle: 10 #???????????
        min-idle: 10 #???????????
        max-active: 10 #????????????????????
        max-wait: -1 #???????????????????????

  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr:
          localhost: 8848

