server:
  port: 8082


spring:
  application:
    name: spring-cloud-reactive-demo
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr:
          localhost: 8848

